services:
  app:
    image: sistema-ingreso-egreso
    env_file:
      - .env.production
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL
        - NEXTAUTH_URL
        - NEXTAUTH_SECRET
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - '4000:3001'
