import type { Metadata } from "next";
import { Providers } from "./providers";
import SidebarWithHeader from "@/components/ui/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <SidebarWithHeader>{children}</SidebarWithHeader>
        </Providers>
      </body>
    </html>
  );
}
